import {
    AdjustmentsHorizontalIcon,
    AdjustmentsVerticalIcon,
    ArchiveBoxIcon,
    ArrowDownTrayIcon,
    ArrowLeftIcon,
    ArrowPathIcon,
    ArrowRightIcon,
    ArrowRightOnRectangleIcon,
    ArrowTopRightOnSquareIcon,
    ArrowTrendingDownIcon,
    ArrowTrendingUpIcon,
    ArrowsPointingOutIcon,
    ArrowsRightLeftIcon,
    BeakerIcon,
    BellAlertIcon,
    BellIcon,
    BoltIcon,
    BookOpenIcon,
    BugAntIcon,
    BuildingOfficeIcon,
    BuildingStorefrontIcon,
    CalendarDaysIcon,
    CalendarIcon,
    ChartBarIcon,
    ChartBarSquareIcon,
    ChatBubbleLeftEllipsisIcon,
    CheckBadgeIcon,
    CheckCircleIcon,
    ChevronDownIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    CircleStackIcon,
    ClipboardDocumentCheckIcon,
    ClipboardDocumentListIcon,
    ClockIcon,
    CloudArrowDownIcon,
    CloudIcon,
    Cog6ToothIcon,
    CpuChipIcon,
    DocumentTextIcon,
    EllipsisVerticalIcon,
    EnvelopeIcon,
    ExclamationCircleIcon,
    ExclamationTriangleIcon,
    EyeIcon,
    FireIcon,
    FunnelIcon,
    GlobeAltIcon,
    HeartIcon,
    InformationCircleIcon,
    LightBulbIcon,
    LockClosedIcon,
    MagnifyingGlassIcon,
    MapIcon,
    MapPinIcon,
    MinusIcon,
    NoSymbolIcon,
    PencilSquareIcon,
    PlusCircleIcon,
    PlusIcon,
    PresentationChartLineIcon,
    QuestionMarkCircleIcon,
    RectangleStackIcon,
    ScaleIcon,
    ServerIcon,
    ShareIcon,
    ShieldCheckIcon,
    SignalIcon,
    SparklesIcon,
    Squares2X2Icon,
    SunIcon,
    TableCellsIcon,
    TagIcon,
    TrashIcon,
    UserCircleIcon,
    UserIcon,
    UserPlusIcon,
    UsersIcon,
    WrenchScrewdriverIcon,
    XCircleIcon,
    XMarkIcon,
} from '@heroicons/react/24/outline'

const ICONS = {
    account_circle:       UserCircleIcon,
    add:                  PlusIcon,
    add_chart:            PresentationChartLineIcon,
    add_circle:           PlusCircleIcon,
    add_location:         MapPinIcon,
    add_location_alt:     MapPinIcon,
    add_task:             ClipboardDocumentCheckIcon,
    admin_panel_settings: ShieldCheckIcon,
    agriculture:          BuildingStorefrontIcon,
    analytics:            ChartBarIcon,
    arrow_back:           ArrowLeftIcon,
    arrow_forward:        ArrowRightIcon,
    assignment:           ClipboardDocumentListIcon,
    block:                NoSymbolIcon,
    bolt:                 BoltIcon,
    build:                WrenchScrewdriverIcon,
    calendar_month:       CalendarDaysIcon,
    calendar_today:       CalendarIcon,
    cancel:               XCircleIcon,
    category:             TagIcon,
    check_circle:         CheckCircleIcon,
    chevron_left:         ChevronLeftIcon,
    chevron_right:        ChevronRightIcon,
    cloud:                CloudIcon,
    cloud_sync:           ArrowPathIcon,
    cloudy_snowing:       CloudIcon,
    close:                XMarkIcon,
    compost:              SparklesIcon,
    cyclone:              ArrowPathIcon,
    database:             CircleStackIcon,
    delete:               TrashIcon,
    dns:                  ServerIcon,
    download:             ArrowDownTrayIcon,
    eco:                  SparklesIcon,
    edit:                 PencilSquareIcon,
    edit_note:            DocumentTextIcon,
    error_outline:        ExclamationCircleIcon,
    event_available:      CalendarDaysIcon,
    expand_more:          ChevronDownIcon,
    file_download:        ArrowDownTrayIcon,
    filter_alt:           FunnelIcon,
    filter_list:          AdjustmentsHorizontalIcon,
    fullscreen:           ArrowsPointingOutIcon,
    grass:                SparklesIcon,
    grid_view:            Squares2X2Icon,
    group:                UsersIcon,
    group_add:            UserPlusIcon,
    groups:               UsersIcon,
    help:                 QuestionMarkCircleIcon,
    help_outline:         QuestionMarkCircleIcon,
    history:              ClockIcon,
    info:                 InformationCircleIcon,
    insights:             LightBulbIcon,
    inventory:            ArchiveBoxIcon,
    inventory_2:          ArchiveBoxIcon,
    ios_share:            ShareIcon,
    keyboard_arrow_down:  ChevronDownIcon,
    language:             GlobeAltIcon,
    layers:               RectangleStackIcon,
    lightbulb:            LightBulbIcon,
    location_on:          MapPinIcon,
    lock:                 LockClosedIcon,
    logout:               ArrowRightOnRectangleIcon,
    mail:                 EnvelopeIcon,
    map:                  MapIcon,
    memory:               CpuChipIcon,
    menu_book:            BookOpenIcon,
    monitor_heart:        HeartIcon,
    more_vert:            EllipsisVerticalIcon,
    my_location:          MapPinIcon,
    notifications:        BellIcon,
    notifications_active: BellAlertIcon,
    open_in_new:          ArrowTopRightOnSquareIcon,
    partly_cloudy_day:    CloudIcon,
    pending:              ClockIcon,
    person:               UserIcon,
    person_add:           UserPlusIcon,
    pest_control:         BugAntIcon,
    policy:               ShieldCheckIcon,
    potted_plant:         SparklesIcon,
    priority_high:        ExclamationTriangleIcon,
    progress_activity:    ArrowPathIcon,
    push_pin:             MapPinIcon,
    query_stats:          ChartBarSquareIcon,
    rainy:                CloudArrowDownIcon,
    rate_review:          ChatBubbleLeftEllipsisIcon,
    refresh:              ArrowPathIcon,
    remove:               MinusIcon,
    scale:                ScaleIcon,
    search:               MagnifyingGlassIcon,
    search_off:           MagnifyingGlassIcon,
    sensors:              SignalIcon,
    settings:             Cog6ToothIcon,
    shield_person:        ShieldCheckIcon,
    show_chart:           ChartBarIcon,
    space_dashboard:      Squares2X2Icon,
    speed:                BoltIcon,
    storage:              CircleStackIcon,
    store:                BuildingStorefrontIcon,
    straighten:           ArrowsRightLeftIcon,
    sunny:                SunIcon,
    table_rows:           TableCellsIcon,
    tag:                  TagIcon,
    thermostat:           FireIcon,
    trending_down:        ArrowTrendingDownIcon,
    trending_flat:        MinusIcon,
    trending_up:          ArrowTrendingUpIcon,
    tune:                 AdjustmentsVerticalIcon,
    verified:             CheckBadgeIcon,
    verified_user:        ShieldCheckIcon,
    visibility:           EyeIcon,
    warehouse:            BuildingOfficeIcon,
    water_drop:           BeakerIcon,
    wb_sunny:             SunIcon,
    warning:              ExclamationTriangleIcon,
}

export default function Icon({ name, className = 'h-5 w-5' }) {
    const Component = ICONS[name]
    if (!Component) return null
    return <Component className={className} aria-hidden="true" />
}
